### ISSUE TITLE
Color calibration without Nvidia Card

### ISSUE THREAD

**Issue by macaodha** [stereolabs/zed-opencv#17]

**Comment by sl-braun** [comment]
Hi,

the ZED SDK does a color matching between left and right image during init()/grab(). Since new 1142 firmware, white balance is done for each sensor independently which reduces color difference between left and right image.
You may try to test without the color correction done in the ZED SDK or with a color correction you can implement by yourself using OpenCV (it may not be real-time however).


Best,
/*OB*/
