### ISSUE TITLE
Multiple main files after cmake operation

### ISSUE THREAD

**Issue by Patelvishal95** [stereolabs/zed-opencv#28]
Hey i ran cmake on your cloned github project. When i build the project after changing the build mode to release. i get the following error code.
Error	2	error LNK1169: one or more multiply defined symbols found	D:\zed-opencv-master\src\Release\ZED with OpenCV.exe	ZED_with_OpenCV
Error	1	error LNK2005: main already defined in CMakeCXXCompilerId.obj	D:\zed-opencv-master\src\main.obj	ZED_with_OpenCV
there seems to be some error in cmake that i am not able to locate.

**Comment by madajimmy** [comment]
You have two main functions in your project.
Delete or comment main function in CMakeCXXCompilerId.obj file and it should be fine.
It locates at the bottom of file.

**Comment by windwolf** [comment]
I got the same problem...

**Comment by crysty936** [comment]
If anyone ever stumbles upon this in the future, it's because most probably you have globbed everything under the CMAKE_CURRENT_LIST_DIR as source files, that includes everything in the Build Folder, which contains source files that should definitely not be in your project. Consider filtering those files from your project.
