### ISSUE TITLE
SDK backward compatibility with old SVOs

### ISSUE THREAD

**Issue by eduardohenriquearnold** [stereolabs/zed-opencv#49]
I have a couple of SVO files recorded with the SDK version 0.9.4 which I need to open. I cannot use that same version because it does not support my current GPU (GTX 1060). When trying to use a newer version that supports my GPU I get the following error: 

``ERROR : Since the version 1.0.0 of the SDK the VGA resolution is 672*376, it seems you try to open an old SVO or you do not have update your firmware.
Unable to init the ZED:ZED_WRONG_FIRMWARE
``

I have already reported this issue and have not had a response from anyone in more than a month, I honestly expected you to have more consideration for your costumers.

**Comment by adujardin** [comment]
Hi,
I understand your frustration. 
However, you should contact the support available at support@stereolabs.com for general issues.
GitHub issues are meant for a specific sample and tend to have less attention, especially for issue not directly related to this sample. Contrary to the support ticket where you'll always get an answer.

In your case, the SDK used was a beta (0.9.X) and subject to breaking changes. You should confirm this with the support but I don't think we have any plan to support older SVO since it's unfortunate but it only affects VGA SVO from the pre-1.0 version with the older firmware and would require extensive changes. 
Sorry
